# See the readme at the top of this dir for the overall domain
# registration / DNS setup

# Note that all DNS names have a period at the end -- apparently this
# is part of the RFC

resources:
  - name: dns-zone
    type: dns.v1.managedZone
    properties:
      name: alexflint-io
      dnsName: alexflint.io.
      description: 'hosted zone for alexflint.io'
  - name: dns-records
    type: gcp-types/dns-v1:resourceRecordSets
    properties:
      name: alexflint.io.
      managedZone: alexflint-io
      records:
        - name: www.alexflint.io.
          type: A
          ttl: 60
          rrdatas:
            - 34.107.158.168  # Google cloud load balancer
        - name: alexflint.io.
          type: A
          ttl: 60
          rrdatas:
            - 34.107.158.168  # Google cloud load balancer
